'''
  83) [CHALLENGE] Create a logic that fills a vector of 20 positions with random
      numbers (between 0 and 99) generated by the computer. Right after that, show the
      generated numbers and then sort the vector in ascending order, finally displaying
      the sorted values.
'''



